### ISSUE TITLE
Do not work

### ISSUE THREAD

**Issue by cjsb** [physhh/PCISPH#2]
Hi again,

with the libs I can compile, but wen I exacute the code stops in
if(glewInit() != GLEW_OK) 

What should I do?
Thank you

**Comment by cjsb** [comment]
Just to add more info...
In the command line is written "GL-Version: 4.5 clGetDeviceIDs: -1"

**Comment by ziish** [comment]
Are you sure the crash happens at the glew initialization? Your output seems like the initialization of OpenCL is not working as expected. clGetDeviceIDs is unable to find a device. You might have to debug what is going wrong. It might have to do with the way the initialization is done - it is a bit weird when you try to get a shared context between OpenCL <=> OpenGL. 

Desipite of that the application was tested on AMD and Nvidia hardware so in theory it should work on most platforms.
